# Generated by Django 4.2.7 on 2023-12-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="tags",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
