name: Run Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: windows-latest  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Flake8 Linter
      run: |
        flake8 .

    - name: Run Black Formatter (Check)
      run: |
        black --check .


